import logo from './logo.svg';
import './App.css';
import './App2.css';
import miImagen from './hrex.PNG';
import giros from './img/giroscopio.PNG';
import term from './img/termistor.png';
import son from './img/sonido.png';
import fot from './img/fotoreceptor.png';
import spc from './img/spcam.png';
import nrf from './img/nrf.png';


import logoinfo from './logoinfo.png';

function App() {
  return (

    <div>
        <header>
            <img src={logoinfo} alt="FIC" id='logoinfo' />

        </header>

        <div id='divisores-principales'>
                  <div className='blankfond'>
                    
                    <div>
                      <h1>Introducing RO</h1>

                        <p className='textogrande'>The RO Project has as its specific purpose the exploration of closed and difficult spaces.
                          access, such as debris barriers, narrow places, medium pipes or,
                          ventilation ducts.
                        </p>
                        </div>
                  </div>

                  <div className='blankfondimg'>
                      <img src={miImagen} alt="RO" id='imghrex' />
                      <p className='descripcionmarco'>RO's first model</p>

                </div>
        </div>
<hr></hr>
        <div id='divisores-principales'>

            <div className='blankfondaux'>
                <h2>Motivation</h2>
                  <p> Landslide accidents are a worldwide problem. The constructions
                      Anti-seismic are not seen in a large number of countries because they do not have tremors or earthquakes
                      occasionally, unlike Chile, a country that has adapted with its constructions before
                      these eventualities. RO Project originates from the consequences generated by this
                      natural disaster, helping in the rescue efforts with the exploration in rubble and
                      landslides, as well as in the prevention of major risks by analyzing areas with danger of
                      collapse.
                  </p>
            </div>

            
        </div>

        <hr></hr>

        
        <div >
              <h2>What are theirs main components?</h2>
            
              <div className='desplegable'>

                  <div className='marco'>
                      <h3>ADXL345 Gyroscope</h3> 
                    
                      <img src={giros} alt="Giro" className='limiteimg' />

                      <p className='descripcionmarco'>Indicates the position in which the RO is in real time.</p>

                  </div>
          
                {/*------------------------------*/}

                  <div className='marco'>
                      <h3>Thermistor</h3> 
                    
                      <img src={term} alt="term" className='limiteimg2' />

                      <p className='descripcionmarco'termistor>It measures the ambient temperature in which the RO is wrapped.</p>

                  </div>

                 {/*------------------------------*/}

                 <div className='marco'>
                      <h3>sound sensor</h3> 
                    
                      <img src={son} alt="son" className='limiteimg2' />

                      <p className='descripcionmarco'>Detect sudden bursts of sound.</p>

                  </div>

                 {/*------------------------------*/}

                 <div className='marco'>
                      <h3>Photoresist</h3> 
                    
                      <img src={fot} alt="fot" className='limiteimg2' />

                      <p className='descripcionmarco'>Measure the light coefficient in which the RO is. </p>

                  </div>

                 {/*------------------------------*/}

                 <div className='marco'>
                      <h3>Camera</h3> 
                    
                      <img src={spc} alt="cam" className='limiteimg2' />

                      <p className='descripcionmarco'>Capture video in real time from the point of view of the RO.</p>

                  </div>

                  {/*------------------------------*/}

                 <div className='marco'>
                      <h3>NRF24L01</h3> 
                    
                      <img src={nrf} alt="nrf" className='limiteimg2' />

                      <p className='descripcionmarco'>Send the video and the values ​​captured by the RO in real time. </p>

                  </div>
              
              </div>

            </div>


            <hr></hr>


        <div className='especificaciones'>

            <h2>Technical specifications</h2>

                  {/* Aportes de la universidad */}


                  <li className='parali'>Arduino UNO x 3</li>
                  <li className='parali'>Arduino NANO</li>

                          {/* AFEL */}

                  <li>Shield Motor L293D </li>
                  <li>Gearmotor N20 6v </li>
                  <li>ESP32-CAM Wi-Fi Bluetooth panel </li>
                  <li>nRF24L01 2.4 Ghz RF Transceiver with SMA, LNA and PA Antenna </li>
                  <li>Battery Holder 18650 x 2</li>
                  <li>Kit 200 Push Buttons</li>
                  <li>Pan-Tilt Servo Support SG90 - Camera - Ultrasonic</li>
                  <li>GY-291 ADXL345 Accelerometer Sensor </li>


                          {/* MECHATRONICSTORE */}

                  <li>Adapter plate for 8-pin NRF24L01 wireless transmitter module</li>
                  <li>Analog joystick module for playstation KY-023 </li>
                  <li>Toggle switch x 3</li>
                  <li>Potentiometer</li>
                  <li>PCB Board one side Perforated Point to Point 9x15cm </li>
                  <li>10K Linear Variable Resistor Stereo Sliding </li>

                          {/* VAPER WORLD */}

                  <li>Samsung Battery 25R INR 18650</li>

                          
                          {/* GLOBALCHILE */}

                  <li>LORA SX1278</li>

            

        </div>

    <footer>
      <div style={{ paddingLeft: 80+"%" }}>
      <small>
      Contacts: 
      </small>
      <li><small>omar.marca@mail.udp.cl </small></li>
      <li><small>felipe.mora_m@mail.udp.cl </small></li>
      <li><small>luis.reyes_h@mail.udp.cl </small></li>
      <li><small>vicente.torresb@mail.udp.cl</small></li>
      </div>

    </footer>

  </div>

  );
}

export default App;
